version: "3"
services:
  standalone-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
    - /dev/shm:/dev/shm
  tests:
    build: .
    depends_on:
      - standalone-chrome